name: 'PR Validation'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  call-shared-workflow:
    uses: clouddrove/github-shared-workflows/.github/workflows/pr_validation.yml@feat/pr-validation
    secrets: inherit
    with:
      types: |
        feat
        fix
        chore
