name: 'PR Validation'
on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate:
    uses: clouddrove/github-shared-workflows/.github/workflows/pr-validation.yml@feat/pr-validation
    secrets: inherit