name: 'PR Validation'

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  validate:
    name: Validate PR
    uses: clouddrove/github-shared-workflows/.github/workflows/pr_validation.yml@feat/pr-validation
    with:
      # Custom PR types for this specific repository
      pr-types: |
        fix
        feat
        docs
        chore
        ci
        test
      # Custom commit types for this specific repository  
      commit-types: |
        feat
        fix
        docs
        test
        chore
      # Require scope in this repository
      require-scope: true
      # Allow WIP PRs
      wip-allowed: true