# name: Checkov
# on:
#   push:
#     branches:
#       - master
# jobs:
#   build:

#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Python 3.8
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.8
#       - name: Test with Checkov
#         id: checkov
#         uses: bridgecrewio/checkov-action@master
#         with:
#           directory: examples/complete
#           framework: terraform 


---
# name: checkov
# # Controls when the workflow will run


# on:
#   # Runs on pull requests
#   pull_request:
#     branches:
#       - master  # Adjust to your default branch
#   workflow_dispatch:
#     inputs:
#       directory:
#         required: true
#         type: string
#         default: '.'
#       continue_on_error:
#         required: true
#         type: string
#         default: 'true'
#       var_file:
#         required: false
#         type: string

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "scan"
#   scan:
#     permissions:
#       contents: read  # for actions/checkout to fetch code
#       security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
#       actions: read  # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
#       - uses: actions/checkout@v4

#       - name: Checkov GitHub Action
#         uses: bridgecrewio/checkov-action@v12.1347.0
#         with:
#           directory: ${{ inputs.directory }}
#           output_format: cli
#           soft_fail: ${{ inputs.continue_on_error }}
#           download_external_modules: false
# ----------------------------------------------
          # config_file: .checkov.yml

      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v3
      #   if: success() || failure()
      #   with:
      #     sarif_file: results.sarif
# name: checkov

# on:
#   pull_request:
#     branches:
#       - master
#   workflow_dispatch:
#     inputs:
#       directory:
#         required: true
#         type: string
#         default: '.'
#       continue_on_error:
#         required: true
#         type: string
#         default: 'true'
#       var_file:
#         required: false
#         type: string

# jobs:
#   scan:
#     permissions:
#       contents: read
#       security-events: write
#       actions: read

#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.8'

#       - name: Cache Checkov
#         uses: actions/cache@v3
#         with:
#           path: ~/.checkov
#           key: ${{ runner.os }}-checkov-${{ hashFiles('**/*.tf') }}
#           restore-keys: |
#             ${{ runner.os }}-checkov-

#       - name: Run Checkov scan
#         id: checkov
#         uses: bridgecrewio/checkov-action@v12
#         with:
#           directory: ${{ inputs.directory }}
#           output_format: cli,sarif
#           soft_fail: ${{ inputs.continue_on_error }}
#           download_external_modules: false
#           output_file_path: console,results.sarif

#       - name: Upload SARIF file
#         uses: github/codeql-action/upload-sarif@v3
#         if: success() || failure()
#         with:
#           sarif_file: results.sarif

# ----------------=====2=========
# name: Security Scan

# on:
#   pull_request:
#     branches:
#       - master
#   workflow_dispatch:
#     inputs:
#       directory:
#         required: true
#         type: string
#         default: '.'
#       continue_on_error:
#         required: true
#         type: string
#         default: 'true'
#       var_file:
#         required: false
#         type: string

# jobs:
#   scan:
#     permissions:
#       contents: read
#       security-events: write
#       actions: read

#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.8'

#       - name: Cache Checkov
#         uses: actions/cache@v3
#         with:
#           path: ~/.checkov
#           key: ${{ runner.os }}-checkov-${{ hashFiles('**/*.tf') }}
#           restore-keys: |
#             ${{ runner.os }}-checkov-

#       - name: Run Checkov scan
#         id: checkov
#         uses: bridgecrewio/checkov-action@v12
#         with:
#           directory: ${{ inputs.directory }}
#           output_format: cli,sarif
#           soft_fail: ${{ inputs.continue_on_error }}
#           download_external_modules: false
#           output_file_path: console,checkov-results.sarif

#       - name: Run Trivy vulnerability scanner
#         uses: aquasecurity/trivy-action@master
#         with:
#           scan-type: 'fs'
#           scan-ref: '.'
#           format: 'sarif'
#           output: 'trivy-results.sarif'
#           severity: 'CRITICAL,HIGH'

#       - name: Upload Checkov SARIF file
#         uses: github/codeql-action/upload-sarif@v3
#         if: success() || failure()
#         with:
#           sarif_file: checkov-results.sarif
#           category: checkov

#       - name: Upload Trivy SARIF file
#         uses: github/codeql-action/upload-sarif@v3
#         if: success() || failure()
#         with:
#           sarif_file: trivy-results.sarif
#           category: trivy


# ---------------------
name: Security Scan

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      directory:
        required: true
        type: string
        default: '.'
      continue_on_error:
        required: true
        type: string
        default: 'true'
      var_file:
        required: false
        type: string

jobs:
  scan:
    permissions:
      contents: read
      security-events: write
      actions: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Cache Checkov
        uses: actions/cache@v3
        with:
          path: ~/.checkov
          key: ${{ runner.os }}-checkov-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-checkov-

      - name: Run Checkov scan
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ inputs.directory }}
          output_format: cli,sarif
          soft_fail: ${{ inputs.continue_on_error }}
          download_external_modules: false
          output_file_path: console,checkov-results.sarif

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Checkov SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: checkov-results.sarif
          category: checkov

      - name: Upload Trivy SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: trivy-results.sarif
          category: trivy



