name:  checkov
on: 
  # this can be trigger based on both master and main branch.
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  checkov:
    uses: clouddrove/github-shared-workflows/.github/workflows/checkov.yml@master # shared workflow 
    with:
     directory: ./
     continue_on_error: true #action will continue on error
